---
title: "R Notebook"
output: html_document
---

```{r}
library(DBI)
library(RPostgres)
library(readr)

readRenviron(".Renviron")

# extract environment variables
db_name <- Sys.getenv("COOLIFY_DB")
db_host <- Sys.getenv("COOLIFY_HOST")
db_port <- Sys.getenv("COOLIFY_PORT")
db_user <- Sys.getenv("COOLIFY_USER")
db_password <- Sys.getenv("COOLIFY_PASSWORD")

# create connection
con <- DBI::dbConnect(drv = RPostgres::Postgres(),
                      host = db_host,
                      port = db_port,
                      dbname = db_name,
                      user = db_user,
                      password = db_password)

```

## Absolute Frequencies for each Question
### Overall N

```{r}
res <- dbSendQuery(con, "SELECT COUNT(respondent_id) FROM respondent_v1")
dbFetch(res)
```

###  Question Based N

No values in q_response_labelled_de_v1 are null
```{r}
question_id <- "q2"
res <- dbSendQuery(con,"SELECT * FROM q_response_labelled_de_v1 WHERE value is null")
dbFetch(res)
```

SQL type of field value doesnt allow string input
```{r}
question_id <- "q2"
res <- dbSendQuery(con,"SELECT * FROM q_response_labelled_de_v1 WHERE value = 'NA'")
dbFetch(res)
```
Simply counting the number of times a question shows up in responses table.
```{r}
question_id <- "q27"
res <- dbSendQuery(con,sprintf("SELECT question_item_id, COUNT(*) FROM q_response_labelled_de_v1 WHERE question_item_ID = '%s' GROUP BY question_item_id", question_id))
dbFetch(res)
```
## Absolute Frequencies for each Question
### Single Choice Questions

```{r}
question_id <- "q1"
res <- dbSendQuery(con, sprintf("SELECT value_label, value, COUNT(value) FROM q_response_labelled_de_v1 WHERE question_item_id = '%s' GROUP BY value, value_label", question_id))
dbFetch(res)
```
### Multiple Choice Questions

```{r}
question_id <- "q27"
res <- dbSendQuery(con, sprintf("SELECT subquestion_id, value, COUNT(value), value_label FROM q_response_labelled_en_v1 WHERE  question_item_id IN ( SELECT question_item_id from q_response_labelled_en_v1 where question_item_id = '%s') GROUP BY value, value_label, subquestion_id", question_id))
dbFetch(res)
```
```{r}
question_id <- "q27"
res <- dbSendQuery(con, sprintf("SELECT subquestion_id FROM q_response_labelled_en_v1 WHERE  question_item_id IN ( SELECT question_item_id from q_response_labelled_en_v1 where question_item_id = '%s') GROUP BY subquestion_id", question_id))
dbFetch(res)
```
```{r}
sub_id <- "q27_SQ001"
res <- dbSendQuery(con, sprintf("SELECT value_label, value, COUNT(value) FROM q_response_labelled_de_v1 WHERE subquestion_id = '%s' GROUP BY value, value_label", sub_id))
dbFetch(res)
```


